# ircb
# Makefile generated by 'gomaker' bbac79d

# use 'make' to gather dependencies and build a (hopefully) static binary

NAME ?= ircb
VERSION ?= 0.0.1
PREFIX ?= /usr/local/bin
VER ?= X
COMMIT=$(shell git rev-parse --verify --short HEAD)
COMMIT ?= ${VER}
RELEASE ?= ${VERSION}${COMMIT}

all:	${NAME}

help:
	@echo ircb - https://github.com/aerth/ircb
	@echo
	@echo make build - build using gc
	@echo make fast - build using cgo
	@echo make d - build with race detector

fast:
	CGO_ENABLED=1 go build -o ${NAME} -x --ldflags "-s -extldflags='-static' -X main.version=${RELEASE}" .

build:
	@echo 'Building ${NAME} version ${RELEASE}'

	CGO_ENABLED=0 go build -o ${NAME} -x --ldflags "-s -extldflags='-static' -X main.version=${RELEASE}" .
	@echo 'Successfully built ${NAME}'


deps:
	go get -d -x -v .

${NAME}: deps build


install:
	@echo 'PREFIX=${PREFIX}'

	@mkdir -p ${PREFIX}
	@mkdir -p ${PREFIX}/mtools
	@mkdir -p ${PREFIX}/tools

	@mv ${NAME} ${PREFIX}/${NAME}

	@echo installing tools:
	cp -nv mtools/* ${PREFIX}/mtools/
	cp -nv tools/* ${PREFIX}/tools/

	@echo 'Successfully installed ${NAME} to ${PREFIX}'

run:
	go run -v -x $(shell ls *.go | grep -v _test.go)


clean:
	@rm -v ${NAME}

d:
	go build -v -race -x
