#!/bin/sh
# -=tool spawn
# spawns an instance of ircb
if [ ! -x ircb ]; then
echo "no ircb exe found"
echo "this is an ircb tool"
echo "use by sending ircb: -=tool spawn"
exit 0
fi

date
echo "spawning a new instance of ircb"
./ircb &
echo "spawned"
exit 0
